DATASETS:
  TRAIN: ["teeth_train"]
  TEST: ["teeth_val"]

DATALOADER:
  NUM_WORKERS: 4

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  AUG:
    HORIZONTAL_FLIP: true
    VERTICAL_FLIP: false
    ROTATION_ANGLE: 10
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    SATURATION: 0.0
    CROP:
      ENABLED: false
      RANGE: [0.8, 0.8] # ignored

SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.003
  WARMUP_METHOD: "linear"
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 200
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: [2000, 2500]
  GAMMA: 0.1
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 30000

TEST:
  EVAL_PERIOD: 30000

MODEL:
  RESNETS:
    DEPTH: 50
  FPN:
    OUT_CHANNELS: 256

  ANCHOR_GENERATOR:
    SIZES: [[16], [32], [64], [128], [256]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]

  RPN:
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.5
    PRE_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TEST: 1000
    NMS_THRESH: 0.7

  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 0.5

OUTPUT_DIR: "./detectron2_output"
